"""Generate a realistic preview of the ML Digest site with sample papers."""
import sys
sys.path.insert(0, "/home/claude/arxiv-digest")
from generate_site import generate_html

sample_papers = [
    {
        "rank": 1,
        "title": "Mamba-3: Gated Linear Attention with Hardware-Aware State Expansion",
        "authors": ["Albert Gu", "Tri Dao", "Ankit Patel"],
        "categories": ["cs.LG"],
        "link": "https://arxiv.org/abs/2503.14001",
        "summary": "Introduces a third-generation selective state space model that unifies gated linear attention with Mamba's selective scan. The new architecture matches Transformer quality on language modeling at 7B scale while maintaining linear-time inference, achieving 4.2× throughput at 32k context.",
        "contributions": [
            "A unified formulation connecting gated linear attention and selective SSMs via a shared recurrence",
            "Hardware-aware state expansion that dynamically adjusts SSM state dimension based on sequence length",
            "SOTA perplexity-throughput tradeoff at 7B parameter scale across 5 language benchmarks",
        ],
        "relevance_tags": ["architectures", "efficiency", "nlp"],
        "rank_rationale": "Major architectural advance unifying two dominant paradigms with strong empirical results at scale.",
    },
    {
        "rank": 2,
        "title": "ReasonVLM: Chain-of-Thought Grounding for Vision-Language Models via Spatial Reasoning Traces",
        "authors": ["Yifan Li", "Zhengyuan Yang", "Jianfeng Gao", "Chunyuan Li"],
        "categories": ["cs.CV", "cs.CL"],
        "link": "https://arxiv.org/abs/2503.14002",
        "summary": "Proposes a training framework that teaches VLMs to produce step-by-step spatial reasoning traces before answering visual questions. By grounding intermediate reasoning steps to image regions, the model achieves 12% improvement on compositional VQA benchmarks and produces interpretable reasoning chains.",
        "contributions": [
            "Spatial reasoning trace format that links each CoT step to bounding box coordinates",
            "Automated pipeline for generating grounded reasoning data from existing VQA datasets",
            "12.3% accuracy gain on GQA and 8.7% on CLEVR-Humans over GPT-4V baseline",
        ],
        "relevance_tags": ["multimodal", "vision", "nlp"],
        "rank_rationale": "Addresses a key VLM weakness with an elegant training approach and large empirical gains.",
    },
    {
        "rank": 3,
        "title": "Scaling Laws for Reinforcement Learning from Human Feedback: A Unified Analysis",
        "authors": ["Jan Leike", "David Krueger", "Tom Brown"],
        "categories": ["cs.LG", "cs.AI"],
        "link": "https://arxiv.org/abs/2503.14003",
        "summary": "Presents the first comprehensive scaling laws for RLHF, covering reward model accuracy, policy optimization efficiency, and alignment tax as functions of model size, data, and compute. Finds that reward model scaling follows different exponents than base LM scaling, with implications for optimal resource allocation.",
        "contributions": [
            "Empirical scaling laws for reward models spanning 125M to 70B parameters",
            "Discovery that alignment tax decreases super-linearly with model scale",
            "Compute-optimal RLHF recipes that reduce training cost by 35% at fixed quality",
        ],
        "relevance_tags": ["rl", "training", "safety", "theory"],
        "rank_rationale": "Fills a critical gap in understanding how RLHF scales, directly actionable for practitioners.",
    },
    {
        "rank": 4,
        "title": "DiffusionPolicy-2: Real-Time Bimanual Manipulation via Cascaded Consistency Models",
        "authors": ["Cheng Chi", "Zhenjia Xu", "Shuran Song"],
        "categories": ["cs.RO", "cs.LG"],
        "link": "https://arxiv.org/abs/2503.14004",
        "summary": "Extends diffusion policy to bimanual robot manipulation by cascading two consistency models — one for high-level task decomposition and one for low-level action generation. Achieves 15Hz real-time control and 89% success rate on 12 bimanual tasks, including cloth folding and object handover.",
        "contributions": [
            "Cascaded consistency model architecture enabling real-time diffusion policy inference",
            "Task decomposition head that breaks bimanual tasks into coordinated single-arm subtasks",
            "89% average success rate across 12 real-world bimanual manipulation tasks",
        ],
        "relevance_tags": ["robotics", "generative", "efficiency"],
        "rank_rationale": "Significant step toward practical bimanual manipulation with real-time diffusion policies.",
    },
    {
        "rank": 5,
        "title": "TokenFormer: Replacing Attention with Learned Token-to-Token Routing",
        "authors": ["Hao Wang", "Yuxuan Zhang", "Quoc Le"],
        "categories": ["cs.LG"],
        "link": "https://arxiv.org/abs/2503.14005",
        "summary": "Proposes replacing the attention mechanism with a learned sparse routing function that directly maps input tokens to output representations. The routing function is parameterized as a lightweight MLP applied per-token, achieving O(n) complexity while retaining 97% of Transformer quality at GPT-2 scale.",
        "contributions": [
            "Token-to-token routing formulation as a drop-in attention replacement",
            "97% quality retention vs dense attention at 3× inference speedup on GPT-2 Medium",
            "Theoretical analysis showing routing capacity scales with hidden dimension, not sequence length",
        ],
        "relevance_tags": ["architectures", "efficiency", "theory"],
        "rank_rationale": "Clean alternative to attention with strong theoretical grounding and practical speedups.",
    },
    {
        "rank": 6,
        "title": "LongBench-v3: Evaluating Long-Context Understanding Beyond Retrieval",
        "authors": ["Yushi Bai", "Xin Lv", "Jiajie Zhang", "Lei Hou", "Juanzi Li"],
        "categories": ["cs.CL"],
        "link": "https://arxiv.org/abs/2503.14006",
        "summary": "Introduces a new benchmark testing whether LLMs genuinely understand long contexts versus simply retrieving information. Features 1,200 multi-step reasoning tasks requiring synthesis across 10+ document sections, revealing that most models scoring >90% on needle-in-a-haystack drop to 40-55% on synthesis tasks.",
        "contributions": [
            "Multi-hop synthesis tasks that cannot be solved by local retrieval patterns",
            "Analysis showing retrieval-style performance poorly predicts reasoning-style performance",
            "1,200 expert-annotated evaluation instances across 6 domains",
        ],
        "relevance_tags": ["evaluation", "nlp"],
        "rank_rationale": "Exposes a critical gap in how we evaluate long-context models.",
    },
    {
        "rank": 7,
        "title": "FlashConv: IO-Aware Depthwise Convolutions for Sub-Quadratic Sequence Modeling",
        "authors": ["Daniel Fu", "Simran Arora", "Christopher Ré"],
        "categories": ["cs.LG"],
        "link": "https://arxiv.org/abs/2503.14007",
        "summary": "Develops fused CUDA kernels for long depthwise convolutions that eliminate HBM bottlenecks, making convolution-based sequence models 2.5× faster than FlashAttention-2 at 8k context. Demonstrates that with proper IO optimization, global convolutions can match SSM throughput while offering better parallelism during training.",
        "contributions": [
            "IO-aware tiling strategy for depthwise convolutions up to 64k kernel size",
            "2.5× wall-clock speedup over FlashAttention-2 at 8k sequence length",
            "Open-source CUDA kernels compatible with PyTorch autograd",
        ],
        "relevance_tags": ["efficiency", "architectures", "training"],
        "rank_rationale": "Systems-level contribution that makes convolution-based models practically competitive.",
    },
    {
        "rank": 8,
        "title": "Constitutional Agents: Self-Correcting Tool Use via Principle-Guided Verification",
        "authors": ["Yoav Goldberg", "Omer Levy", "Timo Schick"],
        "categories": ["cs.AI", "cs.CL"],
        "link": "https://arxiv.org/abs/2503.14008",
        "summary": "Presents a framework where LLM agents verify their own tool-use actions against a set of learned constitutional principles before execution. The self-correction loop reduces harmful or incorrect API calls by 73% on the ToolBench benchmark while maintaining task completion rate.",
        "contributions": [
            "Principle distillation from human feedback to generate tool-use constitutions",
            "73% reduction in harmful API calls with <5% decrease in task success",
            "Generalizes across unseen tools without per-tool fine-tuning",
        ],
        "relevance_tags": ["agents", "safety", "nlp"],
        "rank_rationale": "Practical safety mechanism for LLM agents with minimal performance cost.",
    },
    {
        "rank": 9,
        "title": "Geometric Tokenization: Learning Resolution-Invariant Vision Representations",
        "authors": ["Xinlei Chen", "Kaiming He"],
        "categories": ["cs.CV"],
        "link": "https://arxiv.org/abs/2503.14009",
        "summary": "Replaces fixed-grid patch tokenization with a learned geometric tokenizer that places tokens at image-adaptive locations. Tokens are positioned via predicted keypoints, enabling resolution-invariant representations. Achieves SOTA on detection and segmentation when transferring from 224px pretraining to high-resolution fine-tuning.",
        "contributions": [
            "Differentiable keypoint-based tokenizer as a drop-in ViT patch replacement",
            "Resolution-invariant pretraining that transfers to arbitrary input sizes without interpolation",
            "+2.1 AP on COCO detection when transferring 224px→1024px vs standard ViT",
        ],
        "relevance_tags": ["vision", "architectures"],
        "rank_rationale": "Elegant solution to a longstanding ViT limitation with immediate practical value.",
    },
    {
        "rank": 10,
        "title": "Online DPO: Continuous Preference Optimization with Streaming Human Feedback",
        "authors": ["Rafael Rafailov", "Archit Sharma", "Chelsea Finn"],
        "categories": ["cs.LG", "cs.AI"],
        "link": "https://arxiv.org/abs/2503.14010",
        "summary": "Extends Direct Preference Optimization to the online setting where preferences arrive as a stream. Proposes a replay-weighted DPO objective that avoids catastrophic forgetting of earlier preferences while rapidly adapting to distribution shift. Matches PPO-based RLHF quality with 5× less compute.",
        "contributions": [
            "Online DPO formulation with replay buffer and importance-weighted gradient updates",
            "Theoretical convergence guarantees under non-stationary preference distributions",
            "5× compute reduction vs PPO-RLHF at matched alignment quality on Anthropic-HH",
        ],
        "relevance_tags": ["training", "rl", "optimization"],
        "rank_rationale": "Makes DPO practical for continuous alignment with strong theoretical backing.",
    },
    {
        "rank": 11,
        "title": "NeuralGrasp: Category-Level 6-DoF Grasping via Implicit Shape Completion",
        "authors": ["Yuzhe Qin", "Hao Su", "Xiaolong Wang"],
        "categories": ["cs.RO", "cs.CV"],
        "link": "https://arxiv.org/abs/2503.14011",
        "summary": "Learns to predict 6-DoF grasps for novel object instances by first completing the object's implicit shape from partial point cloud observations. The two-stage approach outperforms direct grasp prediction methods by 15% on unseen categories in real-robot experiments.",
        "contributions": [
            "Shape-conditioned grasp prediction that generalizes to unseen object categories",
            "Implicit shape completion from single-view depth that captures geometry beyond visible surfaces",
            "15% grasp success improvement on 10 unseen YCB categories in real-robot trials",
        ],
        "relevance_tags": ["robotics", "vision", "generative"],
        "rank_rationale": "Strong real-world results on a challenging manipulation problem.",
    },
    {
        "rank": 12,
        "title": "Sparse MoE Distillation: Compressing Mixture-of-Experts into Dense Students",
        "authors": ["Barret Zoph", "Noam Shazeer", "William Fedus"],
        "categories": ["cs.LG"],
        "link": "https://arxiv.org/abs/2503.14012",
        "summary": "Proposes expert-aware distillation that transfers knowledge from sparse MoE teachers into dense student models. By routing-conditioned distillation, a 7B dense student captures 94% of a 56B MoE teacher's quality — significantly better than standard KD which only achieves 87%.",
        "contributions": [
            "Routing-conditioned distillation loss that preserves expert specialization in dense models",
            "94% quality retention when distilling 56B MoE → 7B dense (vs 87% standard KD)",
            "Analysis of which expert specializations are hardest to compress",
        ],
        "relevance_tags": ["training", "efficiency", "architectures"],
        "rank_rationale": "Practical path to deploying MoE quality at dense-model cost.",
    },
    {
        "rank": 13,
        "title": "CausalVideo: Disentangling Motion and Appearance in Video Generation via Causal Inference",
        "authors": ["Lvmin Zhang", "Maneesh Agrawala"],
        "categories": ["cs.CV", "cs.LG"],
        "link": "https://arxiv.org/abs/2503.14013",
        "summary": "Applies causal inference principles to disentangle motion dynamics from visual appearance in video diffusion models. The resulting model allows independent control over object motion trajectories and visual style, enabling applications like motion transfer and appearance editing that prior methods conflate.",
        "contributions": [
            "Causal graph formulation separating motion and appearance latent variables in video diffusion",
            "Independent control of motion trajectories and visual appearance at inference time",
            "New benchmark for evaluating motion-appearance disentanglement with 500 annotated clips",
        ],
        "relevance_tags": ["generative", "vision", "theory"],
        "rank_rationale": "Principled approach to a major video generation challenge with practical applications.",
    },
    {
        "rank": 14,
        "title": "Context Distillation at Scale: Teaching Small LMs to Use 128K Contexts",
        "authors": ["Dacheng Li", "Rulin Shao", "Ari Holtzman"],
        "categories": ["cs.CL"],
        "link": "https://arxiv.org/abs/2503.14014",
        "summary": "Demonstrates that small language models (1-3B) can effectively use 128K contexts when distilled from large long-context teachers. The key insight is progressive context extension during distillation, growing the context window 4× at each stage. A 3B student matches Llama-3-70B on document QA tasks with 128K inputs.",
        "contributions": [
            "Progressive context extension schedule for distillation (4K→16K→64K→128K)",
            "3B model matching 70B teacher quality on SCROLLS and QuALITY at 128K context",
            "Analysis showing attention pattern inheritance is the key mechanism, not just output matching",
        ],
        "relevance_tags": ["nlp", "efficiency", "training"],
        "rank_rationale": "Enables long-context capabilities in deployable model sizes.",
    },
    {
        "rank": 15,
        "title": "AdaptiveGrad: Per-Layer Learning Rate Adaptation via Gradient Distribution Matching",
        "authors": ["Yang You", "Jianwei Yang", "Igor Babuschkin"],
        "categories": ["cs.LG"],
        "link": "https://arxiv.org/abs/2503.14015",
        "summary": "Proposes an optimizer that automatically adapts per-layer learning rates by matching gradient magnitude distributions across layers. Eliminates the need for warmup schedules and learning rate tuning in Transformer training, achieving comparable performance to hand-tuned AdamW across scales from 125M to 13B.",
        "contributions": [
            "Gradient distribution matching criterion for automatic per-layer LR adaptation",
            "Eliminates warmup and LR tuning with no quality loss from 125M to 13B scale",
            "Theoretical connection to natural gradient methods via Fisher information approximation",
        ],
        "relevance_tags": ["optimization", "training", "theory"],
        "rank_rationale": "Quality-of-life improvement for LLM training with solid theoretical grounding.",
    },
]

generate_html(
    papers=sample_papers,
    total_fetched=312,
    categories=["cs.LG", "cs.CL", "cs.AI", "cs.CV", "cs.RO"],
    output_path="/mnt/user-data/outputs/ml-digest-preview.html",
)
